/******************************************************************************/
/***          Generated by IBExpert 2012.02.21 20/05/2021 16:24:50          ***/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES WIN1252;

SET CLIENTLIB 'C:\Softwares\CasaCambio\Source\fbclient.dll';

CREATE DATABASE 'localhost:C:\Softwares\CasaCambio\BD\dados.fdb'
USER 'SYSDBA' PASSWORD 'masterkey'
PAGE_SIZE 16384
DEFAULT CHARACTER SET WIN1252 COLLATION WIN1252;



/******************************************************************************/
/***                               Generators                               ***/
/******************************************************************************/

CREATE GENERATOR GEN_COTACOES_ID;
SET GENERATOR GEN_COTACOES_ID TO 1141;

CREATE GENERATOR GEN_MOEDAS_ID;
SET GENERATOR GEN_MOEDAS_ID TO 247;

CREATE GENERATOR GEN_OPERACOES_ID;
SET GENERATOR GEN_OPERACOES_ID TO 17;



/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/



CREATE TABLE COTACOES (
    ID               INTEGER NOT NULL,
    DATA_COTACAO     DATE,
    CODIGO           SMALLINT,
    TAXA_COMPRA      DOUBLE PRECISION,
    TAXA_VENDA       DOUBLE PRECISION,
    PARIDADE_COMPRA  DOUBLE PRECISION,
    PARIDADE_VENDA   DOUBLE PRECISION
);


CREATE TABLE MOEDAS (
    ID        INTEGER NOT NULL,
    CODIGO    SMALLINT,
    NOME      VARCHAR(60),
    SIMBOLO   VARCHAR(10),
    TIPO      CHAR(1),
    COD_PAIS  SMALLINT,
    PAIS      VARCHAR(50)
);


CREATE TABLE OPERACOES (
    ID                    INTEGER NOT NULL,
    NOME_CLIENTE          VARCHAR(60),
    MOEDA_ORIGEM          VARCHAR(3),
    MOEDA_DESTINO         VARCHAR(3),
    DATA_OPERACAO         DATE,
    VALOR_ORIGINAL        DOUBLE PRECISION,
    VALOR_CONVERTIDO      DOUBLE PRECISION,
    TAXA_COBRADA          DOUBLE PRECISION,
    VALOR_COTACAO         DOUBLE PRECISION,
    IND_CBBMOEDA          SMALLINT,
    CODIGO_MOEDA_ORIGEM   SMALLINT,
    CODIGO_MOEDA_DESTINO  SMALLINT
);




/******************************************************************************/
/***                           Unique Constraints                           ***/
/******************************************************************************/

ALTER TABLE MOEDAS ADD CONSTRAINT UNQ1_MOEDAS UNIQUE (CODIGO);


/******************************************************************************/
/***                              Primary Keys                              ***/
/******************************************************************************/

ALTER TABLE COTACOES ADD CONSTRAINT PK_COTACOES PRIMARY KEY (ID);
ALTER TABLE MOEDAS ADD CONSTRAINT PK_MOEDAS PRIMARY KEY (ID);
ALTER TABLE OPERACOES ADD CONSTRAINT PK_OPERACOES PRIMARY KEY (ID);


/******************************************************************************/
/***                              Foreign Keys                              ***/
/******************************************************************************/

ALTER TABLE COTACOES ADD CONSTRAINT FK_COTACOES_1 FOREIGN KEY (CODIGO) REFERENCES MOEDAS (CODIGO);


/******************************************************************************/
/***                                Triggers                                ***/
/******************************************************************************/


SET TERM ^ ;



/******************************************************************************/
/***                          Triggers for tables                           ***/
/******************************************************************************/



/* Trigger: COTACOES_BI */
CREATE TRIGGER COTACOES_BI FOR COTACOES
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_COTACOES_id,1);
end
^


/* Trigger: MOEDAS_BI */
CREATE TRIGGER MOEDAS_BI FOR MOEDAS
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_moedas_id,1);
end
^


/* Trigger: OPERACOES_BI */
CREATE TRIGGER OPERACOES_BI FOR OPERACOES
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_operacoes_id,1);
end
^


SET TERM ; ^

